spring.application.name=mail.sender

#RabbitMQ
rabbitmq.queuename=reset_password_queue

#Spring Mail
# Configurações SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=campestre.assets@gmail.com
spring.mail.password=chee lgcr wwzd mlne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
